name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: ./Labs-And-Homeworks/Automated-Testing/Library-Catalog/package-lock.json
    - name: Locate package.json directory
      run: cd Labs-And-Homeworks/Automated-Testing/Library-Catalog
    - name: Install dependencies
      run: npm install
    - name: Replace the config settings
      run: echo "export const settings = { host:\"http://localhost:3030\" };" > src/config.js
    - name: Start backend
      run: npm run start-be &
    - name: Sleep for 3 seconds
      run: sleep 3
    - name: Start frontend
      run: npm run start-fe &
    - name: Sleep for 3 seconds
      run: sleep 3
    - name: Install Playwright
      run: npx playwright install
    - name: Execute Playwright UI tests
      run: npm run test-ui
    - name: Run integration tests
      run: npm test
  
  deploy-be:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy Backend to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID_BE }}
          api-key: ${{ secrets.RENDER_TOKEN }}
    
  deploy-fe:
     runs-on: ubuntu-latest
     needs: deploy-be
     steps:
       - name: Deploy Frontend to production
         uses: johnbeynon/render-deploy-action@v0.0.8
         with:
           service-id: ${{ secrets.SERVICE_ID_FE }}
           api-key: ${{ secrets.RENDER_TOKEN }}
