name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./Labs-And-Homeworks/CI-CD-in-Git-Hub-Actions/01.Student-Registry-App/package-lock.json
    - name: Install dependencies
      run: |
        cd Labs-And-Homeworks/CI-CD-in-Git-Hub-Actions/01.Student-Registry-App
        npm install
    - name: Run integration tests
      run: |
        cd Labs-And-Homeworks/CI-CD-in-Git-Hub-Actions/01.Student-Registry-App
        npm test
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
